### ISSUE TITLE
crash on SE

### ISSUE THREAD

**Issue by Arnoymous** [lokalise/lokalise-ios-framework#10]
<img width="1359" alt="capture d ecran 2017-07-09 a 16 57 51" src="https://user-images.githubusercontent.com/10015557/27995010-f8682c80-64c7-11e7-9307-f22f94fd2767.png">
<img width="485" alt="capture d ecran 2017-07-09 a 16 59 40" src="https://user-images.githubusercontent.com/10015557/27995037-0b211378-64c8-11e7-9a8d-3b9a3359771f.png">
<img width="313" alt="capture d ecran 2017-07-09 a 16 59 48" src="https://user-images.githubusercontent.com/10015557/27995038-0b44660c-64c8-11e7-9b8e-111a0a825ab4.png">
<img width="636" alt="capture d ecran 2017-07-09 a 17 00 28" src="https://user-images.githubusercontent.com/10015557/27995048-2778eb22-64c8-11e7-9f19-c054c97e735d.png">

**Comment by Fedya-L** [comment]
Have you tried Troubleshooting section of [Lokalise iOS SDK Documentation](https://docs.lokalise.co/article/mL6XaIoAcw-lokalise-i-os-framework)?

**Comment by Arnoymous** [comment]
yes, i don't have base localization enabled on my .strings
<img width="263" alt="capture d ecran 2017-07-10 a 16 48 38" src="https://user-images.githubusercontent.com/10015557/28023992-c92ee120-658f-11e7-8bac-18af55331e5e.png">

**Comment by Fedya-L** [comment]
Ok. I managed to reproduce the issue. Please update your `Localization native development region` to `French` for now. You can change it by selecting your application target and opening Info tag.
<img width="653" alt="screen shot 2017-07-11 at 11 23 26" src="https://user-images.githubusercontent.com/2362585/28059082-a7b4cdd8-662b-11e7-9ee3-bf9b089d337f.png">
