### ISSUE TITLE
Lokalise framework fails to check for updates;

### ISSUE THREAD

**Issue by Antondomashnev** [lokalise/lokalise-ios-framework#12]
Hi there, first of all thanks for the great service, you're doing amazing job 👍 

Recently our QA department reported that the app localization is not up to date although the strings on lokalise.co were correct.
After small debug session I found out that `checkForUpdatesWithCompletion` method on `Lokalise` instance returns in completion `false` as a value for `updated` flag and `nil` error.

Version of Framework: `0.6.0`
OS version: `9.3`
Platform: `iOS Simulator`

Please let me know if I can be any help and thanks in advance 😄

**Comment by Fedya-L** [comment]
Hi. Can you check what `localizationYype` is set and what `lokaliseBundleVersion`  framework returns before and after updates? Does `lokaliseBundleVersion` match version of newly generated bundle or it 's stuck on an older version?

**Comment by Antondomashnev** [comment]
> Can you check what localizationYype is set

We don't set it explicitly and the default value is `LokaliseLocalizationRelease`.

> What lokaliseBundleVersion framework returns before and after updates

Before: 1496144855
After: 1496144855

> Does lokaliseBundleVersion match version of newly generated bundle or it 's stuck on an older version?

it matches. 

Another note from my side. We use `NSLocalizedString("my key", comment: "")` code to get the localized string. Also we swizzle bundles.

**Comment by Antondomashnev** [comment]
The support helped to resolve the issue. It was a misusage of framework.

**Comment by SergejLogis** [comment]
Would be extremely useful to actually state what was fixed 🙂 I'm facing the same issue at the moment... Thanks.
