### ISSUE TITLE
Bitcode Support

### ISSUE THREAD

**Issue by endoze** [lokalise/lokalise-ios-framework#4]
Can this framework be built with support for [Bitcode](https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html)?

I'd like to continue using Bitcode for my app in the App Store and use this framework.

**Comment by Fedya-L** [comment]
I enabled Bitcode in 0.3.3. Check it out and tell me if it works for you.

**Comment by endoze** [comment]
Works beautifully, thanks for such a quick response and an awesome framework/service
