### ISSUE TITLE
watchOS and tvOS Support

### ISSUE THREAD

**Issue by endoze** [lokalise/lokalise-ios-framework#5]
Can you add support for both watchOS and tvOS in the [Podspec](https://guides.cocoapods.org/syntax/podspec.html#deployment_target)?

I'd like to use this framework and service in a companion watchOS app and a tvOS app.

**Comment by Fedya-L** [comment]
I will enable watchOS and tvOS, but first I need to find and update to dependencies that support these targets.

**Comment by Fedya-L** [comment]
I won't be able to release watchOS and tvOS supported version. However, I will be working on open source swift version which will support them.  I'll keep you informed.

**Comment by endoze** [comment]
@Fedya-L Thank you very much for your quick response in this matter. I'm glad to hear there is an effort to open source a version of this framework and in Swift no less! I love having insight into the code of dependencies that get pulled into my projects.

Keep up the awesome work! :rocket:

**Comment by Fedya-L** [comment]
Thank you for the kind words :)
