### ISSUE TITLE
id<LokaliseDelegate> delegate is missing nullability type specifier.

### ISSUE THREAD

**Issue by arielelkin** [lokalise/lokalise-ios-framework#7]
In `Lokalise.h`,
```
@property (weak, nonatomic) id<LokaliseDelegate> delegate;
```

Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

(Xcode 7.3)

**Comment by Fedya-L** [comment]
Sorry for the long wait. Nullability for delegate now specified in 0.3.4.
